{% set name = "chart-studio" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a17283b62470306d77060b200f13f9749c807dd15613c113d36f8d057f5c7019

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - plotly
    - requests
    - retrying >=1.3.3
    - six

test:
  requires:
    - pip
  imports:
    - chart_studio
  commands:
    - pip check

about:
  home: https://github.com/plotly/plotly.py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    Utilities for interfacing with plotly's Chart Studio. Prior to plotly.py version 4, 
    this functionality was included in the plotly package under the plotly.plotly module. 
    As part of plotly.py version 4, the Chart Studio functionality was removed from the 
    plotly package and released in this chart-studio package.
  summary: This package contains utilities for interfacing with Plotly's Chart Studio service
  doc_url: https://plotly.com/python/chart-studio/
  dev_url: https://github.com/plotly/plotly.py/tree/master/packages/python/chart-studio

extra:
  recipe-maintainers:
    - jonmmease
    - timkpaine
    - dhirschfeld
    - nicolaskruchten
    - emmanuelle
